[package]
name = "AdventOfCode2025"
version = "0.1.0"
authors = ["Ronak Nisher <nisher.ronak@gmail.com>"]
edition = "2024"

[dependencies]
itertools = "0.14.0"
num = "0.4.3"
regex = "1.12.2"

[[bin]]
name = "aoc"
path = "src/main.rs"
